
export const ADD_IMAGE_TYPE = "ADD_IMAGE_TYPE";

export const ADD_ALGORITHM = "ADD_ALGORITHM";

export const REMOVE_IMAGE_TYPE = "REMOVE_IMAGE_TYPE";

export const REMOVE_ALGORITHM = "REMOVE_ALGORITHM";

export const CREATE_CONFIGURATION = "CREATE_CONFIGURATION";

export const RESET_SELECTIONS_AND_CONFIGURATION = "RESET_SELECTIONS_AND_CONFIGURATION";